[features]
seeds = true
skip-lint = false

[programs.devnet]
beatx = "BWgVLeu6iqGrgz76Mu9VNRRmJpEMBTne8e2e7AAtobKL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
